spring:
  application:
    name: gateway-service
  config:
    import:
      - optional:nacos:jackson-config.yaml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      enabled: true
      routes:
        - id: product-route #路由ID, 全局唯一
          uri: lb://product-service #lb 整合负载均衡器LoadBalancer
          predicates:
            - Path=/product/** #断言, 路径匹配的进行路由
      discovery:
        locator:
          enabled: false
server:
  port: 48080