server.port: 8081

spring:
  profiles:
    active: dev
  application:
    name: portal-service
  config:
#    file-extension: yaml
    import:
      - nacos:boot-common.yaml
      - nacos:portal-service.yaml
      - optional:nacos:portal-service-${spring.profiles.active:}.yaml
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        metadata:
          version: 1.0.0
      username: ricoyu
      password: 123456
